version: '3.4'

services:
  envoygateway:
    build: ApiGateways/Envoy

  application-api:
    image: ${DOCKER_REGISTRY-}applicationapi:latest
    build:
      context: .
      dockerfile: Services/Application/Application.Api/Dockerfile

  identity-api:
    image: ${DOCKER_REGISTRY-}identityapi:latest
    build:
      context: .
      dockerfile: Services/Identity/Identity.Api/Dockerfile

